# Generated by Django 3.2.23 on 2024-03-04 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rating', '0053_auto_20240228_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach_Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.SmallIntegerField(default=14, verbose_name='Возраст')),
                ('final_position', models.SmallIntegerField(blank=True, null=True)),
                ('full_season', models.BooleanField(default=True)),
                ('fired_season', models.BooleanField(default=False)),
                ('came_season', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coachstatistic', to='rating.player', verbose_name='Игрок')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coachstatistic', to='rating.season', verbose_name='Сезон')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coachstatistic', to='rating.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Статистика тренера',
                'verbose_name_plural': 'Статистика тренеров',
                'ordering': ('-season',),
            },
        ),
        migrations.AddConstraint(
            model_name='coach_statistic',
            constraint=models.UniqueConstraint(fields=('name', 'team', 'season'), name='unique_coach_statistic'),
        ),
    ]
