# Generated by Django 3.2.23 on 2024-03-04 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0053_auto_20240228_1035'),
        ('coach_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coach_Statistic',
            new_name='CoachStatistic',
        ),
    ]
