# Generated by Django 3.2.23 on 2024-03-24 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0054_auto_20240315_2327'),
        ('coach_app', '0002_rename_coach_statistic_coachstatistic'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='coachstatistic',
            name='unique_coach_statistic',
        ),
        migrations.RemoveField(
            model_name='coachstatistic',
            name='name',
        ),
        migrations.AddField(
            model_name='coachstatistic',
            name='coach_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coachstatistic', to='rating.player', verbose_name='Тренер'),
        ),
    ]
