# Generated by Django 3.2.23 on 2024-06-13 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0056_auto_20240327_2318'),
        ('liga2_players_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatisticPlayers',
            new_name='StatisticPlayer',
        ),
    ]
