# Generated by Django 2.2.19 on 2022-12-26 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Текст')),
                ('year_of_birth', models.SmallIntegerField(verbose_name='Год рождения')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(verbose_name='Год')),
                ('game', models.SmallIntegerField(verbose_name='Игры')),
                ('goal', models.SmallIntegerField(verbose_name='Голы')),
                ('assist', models.SmallIntegerField(verbose_name='Передачи')),
                ('point', models.SmallIntegerField(verbose_name='Очки')),
                ('penalty', models.SmallIntegerField(verbose_name='Штраф')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='rating.Player', verbose_name='Игрок')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='rating.Team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
                'ordering': ('-point',),
            },
        ),
    ]
