# Generated by Django 2.2.19 on 2022-12-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_player_statistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Позиции',
            },
        ),
        migrations.AddField(
            model_name='statistic',
            name='position',
            field=models.TextField(default=1, verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
