# Generated by Django 2.2.19 on 2022-12-27 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_auto_20221227_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='year',
            new_name='year_of_champ',
        ),
        migrations.AlterField(
            model_name='statistic',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='rating.Position', verbose_name='Позиция'),
        ),
    ]
