# Generated by Django 2.2.19 on 2022-12-29 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_auto_20221227_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
            },
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='year_of_champ',
        ),
        migrations.AddField(
            model_name='statistic',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='rating.Season', verbose_name='Сезон'),
            preserve_default=False,
        ),
    ]
