# Generated by Django 2.2.19 on 2023-02-04 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0007_statistic_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistic',
            options={'ordering': ('-point', '-goal', 'game'), 'verbose_name': 'Статистика', 'verbose_name_plural': 'Статистика'},
        ),
    ]
