# Generated by Django 2.2.19 on 2023-03-04 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0010_auto_20230215_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.CreateModel(
            name='Team_for_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='Место')),
                ('games', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('ties', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('points', models.IntegerField()),
                ('points_percentage', models.FloatField()),
                ('goals_for', models.IntegerField()),
                ('goals_against', models.IntegerField()),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_for_tables', to='rating.Team', verbose_name='Команда')),
            ],
        ),
    ]
