# Generated by Django 2.2.19 on 2023-03-04 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0011_auto_20230304_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_for_table',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_for_tables', to='rating.Season', verbose_name='Сезон'),
        ),
    ]
