# Generated by Django 2.2.19 on 2023-03-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0012_team_for_table_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_for_table',
            name='points_percentage',
            field=models.FloatField(default=0),
        ),
    ]
