# Generated by Django 2.2.19 on 2023-03-08 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0013_auto_20230304_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team_for_table',
            options={'ordering': ('-points_percentage',)},
        ),
    ]
