# Generated by Django 2.2.16 on 2023-04-15 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0014_auto_20230308_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='position',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='rating.Position', verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='season',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='rating.Season', verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='team',
            field=models.ForeignKey(blank=True, default=12, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='rating.Team', verbose_name='Команда'),
        ),
    ]
