# Generated by Django 2.2.16 on 2023-05-01 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0016_auto_20230424_0047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team_for_table',
            new_name='TeamForTable',
        ),
        migrations.AlterField(
            model_name='statistic',
            name='season',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='rating.Season', verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='team',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='rating.Team', verbose_name='Команда'),
        ),
    ]
