# Generated by Django 2.2.16 on 2023-06-08 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0017_auto_20230501_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='season',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='rating.Season', verbose_name='Сезон'),
        ),
        migrations.CreateModel(
            name='TeamForTable2Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='Место')),
                ('games', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('ties', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('points', models.IntegerField()),
                ('points_percentage', models.FloatField(default=0)),
                ('goals_for', models.IntegerField()),
                ('goals_against', models.IntegerField()),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_for_tables_2_round', to='rating.Team', verbose_name='Команда')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_for_tables_2_round', to='rating.Season', verbose_name='Сезон')),
            ],
            options={
                'ordering': ('-points_percentage',),
            },
        ),
    ]
