# Generated by Django 2.2.16 on 2023-06-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0018_auto_20230608_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание сезона'),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Название сезона'),
        ),
    ]
