# Generated by Django 2.2.16 on 2023-06-10 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0019_auto_20230609_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamfortable',
            name='coach',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тренер'),
        ),
        migrations.CreateModel(
            name='Playoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер серии')),
                ('study', models.CharField(max_length=10, verbose_name='Стадия')),
                ('result_serie', models.CharField(max_length=4, verbose_name='Результат серии')),
                ('team_1', models.CharField(max_length=25, verbose_name='Команда 1')),
                ('team_2', models.CharField(max_length=25, verbose_name='Команда 2')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playoff', to='rating.Season', verbose_name='Сезон')),
            ],
            options={
                'verbose_name': 'Серия',
                'verbose_name_plural': 'Серии',
            },
        ),
    ]
