# Generated by Django 2.2.16 on 2023-06-10 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0020_auto_20230610_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playoff',
            name='team_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playoff_1', to='rating.Team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='playoff',
            name='team_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='playoff_2', to='rating.Team', verbose_name='Команда'),
        ),
    ]
