# Generated by Django 2.2.16 on 2023-06-11 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0023_auto_20230611_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamfortable2round',
            name='team_for_table_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_for_tables_2_round', to='rating.TeamForTable'),
        ),
    ]
