# Generated by Django 2.2.16 on 2023-06-12 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0024_teamfortable2round_team_for_table_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamfortable',
            options={'ordering': ('season__name',)},
        ),
        migrations.RemoveField(
            model_name='teamfortable2round',
            name='team_for_table_id',
        ),
        migrations.AddField(
            model_name='teamfortable',
            name='round_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_for_tables', to='rating.TeamForTable2Round'),
        ),
    ]
