# Generated by Django 2.2.16 on 2023-06-12 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0025_auto_20230612_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamfortable',
            name='playoff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_for_tables', to='rating.Playoff'),
        ),
    ]
