# Generated by Django 2.2.16 on 2023-06-12 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0026_teamfortable_playoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonPlayoff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=20, verbose_name='Стадия')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_playoff', to='rating.Season', verbose_name='Сезон')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_playoff', to='rating.Team')),
            ],
        ),
        migrations.AlterField(
            model_name='teamfortable',
            name='playoff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_for_tables', to='rating.PersonPlayoff'),
        ),
    ]
