# Generated by Django 2.2.16 on 2023-07-16 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0028_auto_20230716_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='personround2',
            name='table2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rating.TeamForTable2Round2', verbose_name=''),
        ),
        migrations.AddField(
            model_name='personround2',
            name='table3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rating.TeamForTable2Round3', verbose_name=''),
        ),
    ]
