# Generated by Django 2.2.16 on 2023-07-18 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0029_auto_20230716_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamfortable',
            name='round_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_for_tables', to='rating.PersonRound2'),
        ),
    ]
