# Generated by Django 2.2.16 on 2023-07-22 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0031_auto_20230722_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='team',
            field=models.ForeignKey(blank=True, default=8, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='rating.Team', verbose_name='Команда'),
        ),
    ]
