# Generated by Django 2.2.16 on 2023-07-25 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0032_auto_20230722_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistic',
            options={'ordering': ('-season',), 'verbose_name': 'Статистика полевого игрока', 'verbose_name_plural': 'Статистика полевых игроков'},
        ),
        migrations.AlterField(
            model_name='statistic',
            name='team',
            field=models.ForeignKey(blank=True, default=15, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='rating.Team', verbose_name='Команда'),
        ),
        migrations.AddConstraint(
            model_name='statistic',
            constraint=models.UniqueConstraint(fields=('name', 'team', 'season'), name='unique_statistic'),
        ),
    ]
