# Generated by Django 2.2.16 on 2023-08-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0037_auto_20230805_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.TextField(verbose_name='Игрок'),
        ),
    ]
