# Generated by Django 2.2.16 on 2023-08-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0038_auto_20230807_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goalkeeperstatistic',
            options={'ordering': ('-season',), 'verbose_name': 'Статистик Вратаря', 'verbose_name_plural': 'Статистика Вратарей'},
        ),
        migrations.AddConstraint(
            model_name='goalkeeperstatistic',
            constraint=models.UniqueConstraint(fields=('name', 'team', 'season'), name='unique_statistic'),
        ),
    ]
