# Generated by Django 2.2.16 on 2023-08-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0039_auto_20230820_1701'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='goalkeeperstatistic',
            name='unique_statistic',
        ),
        migrations.AddConstraint(
            model_name='goalkeeperstatistic',
            constraint=models.UniqueConstraint(fields=('name', 'team', 'season'), name='unique_goalkeeper_statistic'),
        ),
    ]
