# Generated by Django 2.2.16 on 2023-08-20 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0040_auto_20230820_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalkeeperstatistic',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goalkeeperstatistic', to='rating.Player', verbose_name='Игрок'),
        ),
        migrations.AlterField(
            model_name='goalkeeperstatistic',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goalkeeperstatistic', to='rating.Season', verbose_name='Сезон'),
        ),
    ]
