# Generated by Django 2.2.16 on 2023-08-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0041_auto_20230820_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goalkeeperstatistic',
            options={'ordering': ('-season',), 'verbose_name': 'Статистика Вратаря', 'verbose_name_plural': 'Статистика Вратарей'},
        ),
    ]
