# Generated by Django 2.2.16 on 2023-09-20 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0043_auto_20230820_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamfortable2',
            name='round_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_for_tables2', to='rating.PersonRound2'),
        ),
        migrations.AlterField(
            model_name='teamfortable3',
            name='round_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_for_tables3', to='rating.PersonRound2'),
        ),
        migrations.AlterField(
            model_name='teamfortable4',
            name='round_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_for_tables4', to='rating.PersonRound2'),
        ),
    ]
