# Generated by Django 2.2.16 on 2023-10-08 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0044_auto_20230920_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamfortable2round',
            options={'ordering': ('season__name',), 'verbose_name': 'Команда 1 группы 2 раунда', 'verbose_name_plural': 'Команды 1 группы 2 раунда'},
        ),
        migrations.AlterModelOptions(
            name='teamfortable2round2',
            options={'ordering': ('season__name',), 'verbose_name': 'Команда 2 группы 2 раунда', 'verbose_name_plural': 'Команды 2 группы 2 раунда'},
        ),
        migrations.AlterModelOptions(
            name='teamfortable2round3',
            options={'ordering': ('season__name',), 'verbose_name': 'Команда 3 группы 2 раунда', 'verbose_name_plural': 'Команды 3 группы 2 раунда'},
        ),
    ]
