# Generated by Django 2.2.16 on 2023-10-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0045_auto_20231008_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='emblem',
            field=models.ImageField(blank=True, upload_to='emblem/', verbose_name='Эмблема'),
        ),
    ]
