# Generated by Django 3.2.23 on 2024-02-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0047_player_wikip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='wikip',
            field=models.URLField(blank=True, max_length=250, verbose_name='Ссылка на википедию'),
        ),
    ]
