# Generated by Django 3.2.23 on 2024-02-25 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0048_alter_player_wikip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamfortable',
            name='coach',
        ),
    ]
