# Generated by Django 3.2.23 on 2024-02-28 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0052_auto_20240228_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamfortable4',
            name='coach_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_for_tables4_coach_1', to='rating.player', verbose_name='Тренер'),
        ),
        migrations.AddField(
            model_name='teamfortable4',
            name='coach_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_for_tables4_coach_2', to='rating.player', verbose_name='Тренер_2'),
        ),
        migrations.AddField(
            model_name='teamfortable4',
            name='coach_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_for_tables4_coach_3', to='rating.player', verbose_name='Тренер_3'),
        ),
    ]
