# Generated by Django 3.2.23 on 2024-03-15 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0053_auto_20240228_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamfortable',
            name='coach_1',
        ),
        migrations.RemoveField(
            model_name='teamfortable',
            name='coach_2',
        ),
        migrations.RemoveField(
            model_name='teamfortable',
            name='coach_3',
        ),
        migrations.RemoveField(
            model_name='teamfortable2',
            name='coach_1',
        ),
        migrations.RemoveField(
            model_name='teamfortable2',
            name='coach_2',
        ),
        migrations.RemoveField(
            model_name='teamfortable2',
            name='coach_3',
        ),
        migrations.RemoveField(
            model_name='teamfortable3',
            name='coach_1',
        ),
        migrations.RemoveField(
            model_name='teamfortable3',
            name='coach_2',
        ),
        migrations.RemoveField(
            model_name='teamfortable3',
            name='coach_3',
        ),
        migrations.RemoveField(
            model_name='teamfortable4',
            name='coach_1',
        ),
        migrations.RemoveField(
            model_name='teamfortable4',
            name='coach_2',
        ),
        migrations.RemoveField(
            model_name='teamfortable4',
            name='coach_3',
        ),
    ]
