# Generated by Django 3.2.23 on 2024-03-25 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coach_app', '0003_auto_20240324_2315'),
        ('rating', '0054_auto_20240315_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamfortable',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coach_app.coachstatistic'),
        ),
    ]
