# Generated by Django 3.2.23 on 2025-04-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0056_auto_20240327_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='emblem',
            field=models.ImageField(blank=True, upload_to='photo/', verbose_name='Фото'),
        ),
    ]
