# Generated by Django 3.2.23 on 2025-04-08 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0057_player_emblem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='emblem',
            new_name='photo',
        ),
    ]
