# Generated by Django 3.2.23 on 2025-12-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0058_rename_emblem_player_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='emblem_season',
            field=models.ImageField(blank=True, upload_to='emblem_season/', verbose_name='Эмблема сезона'),
        ),
    ]
