# Generated by Django 3.2.23 on 2025-12-28 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0059_season_emblem_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_image', models.CharField(blank=True, max_length=50, verbose_name='название фотографии')),
                ('image_team', models.ImageField(blank=True, upload_to='image_team/', verbose_name='фото команды')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_team', to='rating.season', verbose_name='Сезон')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_team', to='rating.team', verbose_name='Команда')),
            ],
        ),
    ]
