# Generated by Django 3.2.23 on 2025-12-28 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0060_imageteam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageteam',
            options={'verbose_name': 'Фотография команды', 'verbose_name_plural': 'Фотографии команды'},
        ),
        migrations.AddConstraint(
            model_name='imageteam',
            constraint=models.UniqueConstraint(fields=('season', 'team'), name='unique_image'),
        ),
    ]
