# Generated by Django 3.2.23 on 2026-01-03 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0061_auto_20251228_2302'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='imageteam',
            name='unique_image',
        ),
    ]
