# Generated by Django 3.2.23 on 2024-05-09 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rating', '0056_auto_20240327_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='Место')),
                ('current_name', models.CharField(blank=True, max_length=50, verbose_name='Текущее название')),
                ('games', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('ties', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('points', models.IntegerField()),
                ('points_percentage', models.FloatField(default=0)),
                ('goals_for', models.IntegerField()),
                ('goals_against', models.IntegerField()),
                ('coach_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_in_tables_coach_1', to='rating.player', verbose_name='Тренер')),
                ('coach_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_in_tables_coach_2', to='rating.player', verbose_name='Тренер_2')),
                ('coach_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_in_tables_coach_3', to='rating.player', verbose_name='Тренер_3')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_in_tables', to='rating.team', verbose_name='Команда')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_in_tables', to='rating.season', verbose_name='Сезон')),
            ],
            options={
                'verbose_name': 'Команда основной или 1 группы 1 раунда',
                'verbose_name_plural': 'Команды основной или 1 группы 1 раунда',
                'ordering': ('season__name',),
            },
        ),
    ]
