# Generated by Django 3.2.23 on 2024-05-09 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liga2_seasons_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamintable',
            name='goals_against',
        ),
        migrations.RemoveField(
            model_name='teamintable',
            name='goals_for',
        ),
    ]
