# Generated by Django 3.2.23 on 2024-05-17 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0056_auto_20240327_2318'),
        ('liga2_seasons_app', '0002_auto_20240509_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='Место')),
                ('current_name', models.CharField(max_length=50, verbose_name='Текущее название')),
                ('games', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('ties', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('points', models.IntegerField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_in_add_tables', to='rating.season', verbose_name='Сезон')),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_in_add_tables', to='rating.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Команда дополнителного турнира',
                'verbose_name_plural': 'Команды дополнительного турнира',
            },
        ),
        migrations.CreateModel(
            name='DescriptionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transition_tournament', models.CharField(blank=True, max_length=50, verbose_name='Переходный турнир')),
                ('description_1tb', models.CharField(blank=True, max_length=50, verbose_name='Название таблицы 1')),
                ('description_2tb', models.CharField(blank=True, max_length=50, verbose_name='Название таблицы 2')),
                ('description_3tb', models.CharField(blank=True, max_length=50, verbose_name='Название таблицы 3')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='description_table_liga2', to='rating.season', verbose_name='Сезон')),
            ],
        ),
        migrations.CreateModel(
            name='TeamInTable1gr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='Место')),
                ('current_name', models.CharField(blank=True, max_length=50, verbose_name='Текущее название')),
                ('games', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('ties', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('points', models.IntegerField()),
                ('coach_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_in_tables_coach_1', to='rating.player', verbose_name='Тренер')),
                ('coach_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_in_tables_coach_2', to='rating.player', verbose_name='Тренер_2')),
                ('coach_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_in_tables_coach_3', to='rating.player', verbose_name='Тренер_3')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_in_tables', to='rating.season', verbose_name='Сезон')),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_in_tables', to='rating.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Команда основной или 1 группы 1 раунда',
                'verbose_name_plural': 'Команды основной или 1 группы 1 раунда',
                'ordering': ('season__name',),
            },
        ),
        migrations.CreateModel(
            name='TeamInTable2gr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='Место')),
                ('current_name', models.CharField(blank=True, max_length=50, verbose_name='Текущее название')),
                ('games', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('ties', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('points', models.IntegerField()),
                ('coach_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_in_2_tables_coach_1', to='rating.player', verbose_name='Тренер')),
                ('coach_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_in_2_tables_coach_2', to='rating.player', verbose_name='Тренер_2')),
                ('coach_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_in_2_tables_coach_3', to='rating.player', verbose_name='Тренер_3')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_in_2_tables', to='rating.season', verbose_name='Сезон')),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_in_2_tables', to='rating.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Команда второй группы',
                'verbose_name_plural': 'Команды второй группы',
                'ordering': ('season__name',),
            },
        ),
        migrations.CreateModel(
            name='TransitionTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_real', models.IntegerField(verbose_name='Место для формирования таблицы')),
                ('rank_pict', models.IntegerField(verbose_name='Место выводимое на экран')),
                ('current_name', models.CharField(max_length=50, verbose_name='Текущее имя')),
                ('games', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('ties', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('points', models.IntegerField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_in_transtour', to='rating.season', verbose_name='Сезон')),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Команда переходного турнира',
                'verbose_name_plural': 'Команды переходного турнира',
            },
        ),
        migrations.DeleteModel(
            name='TeamInTable',
        ),
    ]
