# Generated by Django 3.2.23 on 2024-05-18 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0056_auto_20240327_2318'),
        ('liga2_seasons_app', '0003_auto_20240517_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamintable1gr',
            options={'ordering': ('season__name',), 'verbose_name': 'Команда 1 группы', 'verbose_name_plural': 'Команды 1 группы'},
        ),
        migrations.AddField(
            model_name='teamintable1gr',
            name='transition_tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liga2_seasons_app.transitiontournament', verbose_name='Участие в переходном турнире'),
        ),
        migrations.AddField(
            model_name='teamintable2gr',
            name='transition_tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liga2_seasons_app.transitiontournament', verbose_name='Участие в переходном турнире'),
        ),
        migrations.CreateModel(
            name='TransitionSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_1', models.CharField(max_length=10, verbose_name='Счет матча 1')),
                ('game_2', models.CharField(max_length=10, verbose_name='Счет матча 2')),
                ('game_3', models.CharField(max_length=10, verbose_name='Счет матча 3')),
                ('game_4', models.CharField(max_length=10, verbose_name='Счет матча 4')),
                ('team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_in_transserie', to='rating.team', verbose_name='Команда')),
                ('team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_in_transserie', to='rating.team', verbose_name='Команда')),
            ],
        ),
        migrations.AddField(
            model_name='teamintable1gr',
            name='transition_serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liga2_seasons_app.transitionserie', verbose_name='Участие в переходной серии'),
        ),
        migrations.AddField(
            model_name='teamintable2gr',
            name='transition_serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liga2_seasons_app.transitionserie', verbose_name='Участие в переходной серии'),
        ),
    ]
