# Generated by Django 3.2.23 on 2024-05-19 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga2_seasons_app', '0004_auto_20240518_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamintable1gr',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
