# Generated by Django 3.2.23 on 2024-05-19 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0056_auto_20240327_2318'),
        ('liga2_seasons_app', '0005_alter_teamintable1gr_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamintable1gr',
            name='team_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_in_tables', to='rating.team', verbose_name='Команда'),
        ),
    ]
