# Generated by Django 3.2.23 on 2024-05-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga2_seasons_app', '0007_alter_transitiontournament_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaltournament',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
