# Generated by Django 3.2.23 on 2024-05-22 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liga2_seasons_app', '0008_alter_additionaltournament_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamintable1gr',
            name='additional_tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liga2_seasons_app.additionaltournament', verbose_name='Участие в доп.турнире'),
        ),
    ]
