# Generated by Django 3.2.23 on 2024-05-22 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0056_auto_20240327_2318'),
        ('liga2_seasons_app', '0009_teamintable1gr_additional_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transitiontournament',
            name='team_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rating.team', verbose_name='Команда'),
        ),
    ]
