# Generated by Django 3.2.23 on 2024-05-30 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0056_auto_20240327_2318'),
        ('liga2_seasons_app', '0010_alter_transitiontournament_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalTournamentSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='Место')),
                ('current_name', models.CharField(max_length=50, verbose_name='Текущее название')),
                ('games', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('ties', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('points', models.IntegerField(default=0)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_in_add_tables_2', to='rating.season', verbose_name='Сезон')),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_in_add_tables_2', to='rating.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Команда дополнителного турнира',
                'verbose_name_plural': 'Команды дополнительного турнира',
            },
        ),
    ]
