# Generated by Django 3.2.23 on 2024-05-31 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liga2_seasons_app', '0011_additionaltournamentsecond'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionaltournamentsecond',
            options={'verbose_name': 'Команда второго дополнителного турнира', 'verbose_name_plural': 'Команды второго дополнительного турнира'},
        ),
    ]
