# Generated by Django 3.2.23 on 2024-06-01 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liga2_seasons_app', '0012_alter_additionaltournamentsecond_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamintable1gr',
            name='additional_tournament_second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liga2_seasons_app.additionaltournamentsecond', verbose_name='Участие во втором доп.турнире'),
        ),
    ]
