# Generated by Django 3.2.23 on 2024-06-04 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liga2_seasons_app', '0013_teamintable1gr_additional_tournament_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamintable2gr',
            name='additional_tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liga2_seasons_app.additionaltournament', verbose_name='Участие в доп.турнире'),
        ),
        migrations.AddField(
            model_name='teamintable2gr',
            name='additional_tournament_second',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liga2_seasons_app.additionaltournamentsecond', verbose_name='Участие во втором доп.турнире'),
        ),
    ]
