# Generated by Django 3.2.23 on 2024-06-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga2_seasons_app', '0014_auto_20240604_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptiontable',
            name='description_4tb',
            field=models.CharField(blank=True, max_length=50, verbose_name='Восток'),
        ),
        migrations.AlterField(
            model_name='descriptiontable',
            name='description_1tb',
            field=models.CharField(blank=True, max_length=50, verbose_name='Основной турнир или Запад'),
        ),
        migrations.AlterField(
            model_name='descriptiontable',
            name='description_2tb',
            field=models.CharField(blank=True, max_length=50, verbose_name='Дополнительный турнир'),
        ),
        migrations.AlterField(
            model_name='descriptiontable',
            name='description_3tb',
            field=models.CharField(blank=True, max_length=50, verbose_name='Второй доп турнир'),
        ),
    ]
