# Generated by Django 3.2.23 on 2024-06-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga2_seasons_app', '0015_auto_20240604_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamintable2gr',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
