# Generated by Django 3.2.23 on 2024-06-05 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0056_auto_20240327_2318'),
        ('liga2_seasons_app', '0016_alter_teamintable2gr_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitionWithoutPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='Место в таблице')),
                ('current_name', models.CharField(max_length=50, verbose_name='Текущее имя')),
                ('games', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('ties', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('points', models.IntegerField(default=0)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='without_points', to='rating.season', verbose_name='Сезон')),
                ('team_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rating.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Команда переходного турнира',
                'verbose_name_plural': 'Команды переходного турнира',
            },
        ),
    ]
