# Generated by Django 3.2.23 on 2024-06-06 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liga2_seasons_app', '0018_auto_20240605_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamintable1gr',
            name='transition_tournament_without_points',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='liga2_seasons_app.transitionwithoutpoints', verbose_name='Участие в перех т-ре без учета ранее набранных очков'),
        ),
        migrations.AddField(
            model_name='teamintable2gr',
            name='transition_tournament_without_points',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='liga2_seasons_app.transitionwithoutpoints', verbose_name='Участие в перех т-ре без учета ранее набранных очков'),
        ),
    ]
