# Generated by Django 3.2.23 on 2024-06-07 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0056_auto_20240327_2318'),
        ('liga2_seasons_app', '0019_auto_20240606_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalTournamentWithoutPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='Место')),
                ('current_name', models.CharField(max_length=50, verbose_name='Текущее название')),
                ('games', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('ties', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('points', models.IntegerField(default=0)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_tournament_without_points', to='rating.season', verbose_name='Сезон')),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_tournament_without_points', to='rating.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Команда доп т-ра без учета набранных ранее очков',
                'verbose_name_plural': 'Команды доп т-ра без учета набранных ранее очков',
            },
        ),
        migrations.AddField(
            model_name='teamintable1gr',
            name='additional_tournament_without_points',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='liga2_seasons_app.additionaltournamentwithoutpoints', verbose_name='Участие в доп т-ре без учета ранее набранных очков'),
        ),
        migrations.AddField(
            model_name='teamintable2gr',
            name='additional_tournament_without_points',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='liga2_seasons_app.additionaltournamentwithoutpoints', verbose_name='Участие в доп т-ре без учета ранее набранных очков'),
        ),
    ]
