# Generated by Django 3.2.23 on 2024-06-08 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liga2_seasons_app', '0020_auto_20240607_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamintable2gr',
            name='transition_tournament',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='liga2_seasons_app.transitiontournament', verbose_name='Участие в переходном турнире'),
        ),
    ]
