# Generated by Django 3.2.23 on 2025-12-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liga2_seasons_app', '0022_auto_20250420_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='descriptiontable',
            name='description_season',
            field=models.TextField(blank=True, verbose_name='Описание сезона'),
        ),
    ]
